name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Apply Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: $${{ runner.os }}-gradle

      - name: Get Short Identifier
        uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Build
        id: build
        env:
          VERSION_IDENTIFIER: SNAPSHOT+${{ steps.short-sha.outputs.sha }}
        run: ./gradlew :build :githubActionOutput --stacktrace

      - name: GitHub Action Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ steps.build.outputs.artifact_path }}
